apiVersion: apps/v1
kind: Deployment
metadata:
  name: knet-timer-server
spec:
  selector:
    matchLabels:
      knet: timer-server
  replicas: 1
  template:
    metadata:
      labels:
        knet: timer-server
    spec:
      containers:
        - name: tcp-server
          # This is the import path for the Go binary to build and run.
          image: ko://github.com/yangl900/knet/timer-server
          ports:
            - containerPort: 8005
            - containerPort: 8600
        - name: tcpdump
          image: corfr/tcpdump
          command:
            - "/usr/sbin/tcpdump"
            - "-i"
            - "any"
            - "-nn"
---
apiVersion: v1
kind: Service
metadata:
  name: knet
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "1"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: default
    port: 8005
    protocol: TCP
    targetPort: 8005
  - name: hour
    port: 8600
    protocol: TCP
    targetPort: 8600
  selector:
    knet: timer-server
  sessionAffinity: None
  type: LoadBalancer